version: '2'

services:
  redis:
    extends:
      file: docker-compose-common.yml
      service: redis
    restart: always

  postgres:
    extends:
      file: docker-compose-common.yml
      service: postgres
    restart: always

  api:
    extends:
      file: docker-compose-common.yml
      service: api-production
    command: uwsgi --emperor uwsgi.ini
    depends_on:
      - redis
      - postgres
    working_dir: /srv/www/api

  celerybeat:
    extends:
      file: docker-compose-common.yml
      service: api-production
    command: celery -A api beat -l info
    depends_on:
      - redis
      - postgres
      - api

  celeryworker:
    extends:
      file: docker-compose-common.yml
      service: api-production
    command: celery -A api worker -l info
    depends_on:
      - redis
      - postgres
      - api

  nginx:
    extends:
      file: docker-compose-common.yml
      service: nginx
