FROM ebar0n/python-3.5-gis

RUN install -y postgresql-client gettext

# Requirements

COPY ./requirements/base.pip /requirements/base.pip
COPY ./requirements/development.pip /requirements/development.pip

RUN pip install -r /requirements/development.pip
