FROM ebar0n/python-3.5-gis

RUN apt-get update && apt-get install -y postgresql-client \
    gettext

# Requirements

COPY ./requirements/base.pip /requirements/base.pip
COPY ./requirements/production.pip /requirements/production.pip

RUN pip install -r /requirements/production.pip
