FROM ebar0n/python-3.5-gis

RUN apt-get update && apt-get install -y postgresql-client \
    gettext --no-install-recommends && rm -rf /var/lib/apt/lists/*

# Requirements

COPY ./requirements/base.pip /requirements/base.pip
RUN pip install -r /requirements/base.pip

COPY ./requirements/development.pip /requirements/development.pip
RUN pip install -r /requirements/development.pip
