version: '2'

services:
  redis:
    image: redis:latest

  postgres:
    image: mdillon/postgis:9.5
    volumes:
      - ./.data:/var/lib/postgresql/data
    env_file: ./.env
    ports:
      - "15432:5432"

  nginx:
    env_file: ./.env
    volumes:
      - ./public/:/srv/www/public/
      - ./run:/srv/www/run

  api-develoment:
    build:
      context: .
      dockerfile: Dockerfile-Development
    env_file: ./.env
    volumes:
      - ./api:/srv/www/api
      - ./public:/srv/www/public

  api-production:
    build:
      context: .
      dockerfile: Dockerfile-Production
    env_file: ./.env
    volumes:
      - ./public:/srv/www/public
      - ./run:/srv/www/run
    restart: always
