version: '2'

services:
  redis:
    image: redis:latest

  postgres:
    image: mdillon/postgis:9.5
    volumes:
      - ./.data:/var/lib/postgresql/data
    env_file: ./.env
    ports:
      - "15432:5432"

  nginx:
    build: ./compose/nginx
    env_file: ./.env
    ports:
      - "80:80"
    volumes:
      - ./public/:/srv/www/public/
      - ./run:/srv/www/run
    restart: always

  api-develoment:
    image: ebar0n/d-packagebackend:dev
    #build:
    #  context: .
    #  dockerfile: Dockerfile-Development
    env_file: ./.env
    volumes:
      - ./api:/srv/www/api
      - ./public:/srv/www/public

  api-production:
    image: ebar0n/d-packagebackend:pro
    env_file: ./.env
    volumes:
      - ./api:/srv/www/api
      - ./public:/srv/www/public
      - ./run:/srv/www/run
    restart: always
