# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 14:15
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sw_users', '0004_auto_20161113_1920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientaccount',
            options={'verbose_name': 'client', 'verbose_name_plural': 'clients'},
        ),
        migrations.AlterModelOptions(
            name='serviceaccount',
            options={'verbose_name': 'service provider', 'verbose_name_plural': 'services provider'},
        ),
        migrations.AlterModelOptions(
            name='useraccount',
            options={'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
        migrations.AddField(
            model_name='serviceaccount',
            name='last_location_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last location date'),
        ),
        migrations.AddField(
            model_name='serviceaccount',
            name='last_location_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='last location point'),
        ),
        migrations.AlterField(
            model_name='clientaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='clientaccount',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='clientaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='serviceaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='serviceaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='check_mail',
            field=models.BooleanField(default=False, verbose_name='check mail'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='client',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sw_users.ClientAccount', verbose_name='client'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='service',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sw_users.ServiceAccount', verbose_name='service provider'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='stripe_customer',
            field=models.CharField(blank=True, max_length=64, verbose_name='stripe, customer ID'),
        ),
    ]
