# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 07:08
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sw_users', '0005_auto_20161118_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='client',
            field=models.OneToOneField(
                editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='sw_users.ClientAccount',
                verbose_name='client'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='service',
            field=models.OneToOneField(
                editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='sw_users.ServiceAccount',
                verbose_name='service provider'),
        ),
    ]
