# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 00:53
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sw_users', '0006_auto_20161121_0708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientaccount',
            options={'verbose_name': 'cliente', 'verbose_name_plural': 'clientes'},
        ),
        migrations.AlterModelOptions(
            name='serviceaccount',
            options={'verbose_name': 'proveedor de servicio', 'verbose_name_plural': 'proveedor de servicios'},
        ),
        migrations.AlterField(
            model_name='clientaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado a las'),
        ),
        migrations.AlterField(
            model_name='clientaccount',
            name='phone',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999999999)], verbose_name='teléfono'),
        ),
        migrations.AlterField(
            model_name='clientaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='actualizado a las'),
        ),
        migrations.AlterField(
            model_name='serviceaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado a las'),
        ),
        migrations.AlterField(
            model_name='serviceaccount',
            name='driver_license',
            field=models.ImageField(blank=True, upload_to='license', verbose_name='Licencia de conducir'),
        ),
        migrations.AlterField(
            model_name='serviceaccount',
            name='identity_card',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999999)], verbose_name='Cedula de identidad'),
        ),
        migrations.AlterField(
            model_name='serviceaccount',
            name='last_location_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='última fecha de ubicación'),
        ),
        migrations.AlterField(
            model_name='serviceaccount',
            name='last_location_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='último punto de ubicación'),
        ),
        migrations.AlterField(
            model_name='serviceaccount',
            name='phone',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999999999)], verbose_name='teléfono'),
        ),
        migrations.AlterField(
            model_name='serviceaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='actualizado a las'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='check_mail',
            field=models.BooleanField(default=False, verbose_name='correo chekeado'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='client',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='sw_users.ClientAccount', verbose_name='cliente'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='service',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='sw_users.ServiceAccount', verbose_name='proveedor de servicio'),
        ),
    ]
