# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 01:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sw_users', '0007_auto_20161123_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaccount',
            name='phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'Longitud 11')], verbose_name='teléfono'),
        ),
        migrations.AlterField(
            model_name='serviceaccount',
            name='phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'Longitud 11')], verbose_name='teléfono'),
        ),
    ]
