# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 02:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sw_users', '0008_auto_20161123_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaccount',
            name='phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'El numero telefonico tiene que tener una longitud de 11 numeros')], verbose_name='teléfono'),
        ),
        migrations.AlterField(
            model_name='serviceaccount',
            name='identity_card',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Cedula de identidad'),
        ),
        migrations.AlterField(
            model_name='serviceaccount',
            name='phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'El numero telefonico tiene que tener una longitud de 11 numeros')], verbose_name='teléfono'),
        ),
    ]
