# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 04:50
from __future__ import unicode_literals

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sw_users', '0010_auto_20161123_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaccount',
            name='phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'The telephone number must be 11 numbers long')], verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='serviceaccount',
            name='address',
            field=models.CharField(max_length=100, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='serviceaccount',
            name='balance',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6, verbose_name='balance'),
        ),
        migrations.AlterField(
            model_name='serviceaccount',
            name='bankaccount',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sw_payments.BankAccount', verbose_name='bank account'),
        ),
        migrations.AlterField(
            model_name='serviceaccount',
            name='birthdate',
            field=models.DateField(verbose_name='birthdate'),
        ),
        migrations.AlterField(
            model_name='serviceaccount',
            name='driver_license',
            field=models.ImageField(blank=True, upload_to='license', verbose_name="driver's license"),
        ),
        migrations.AlterField(
            model_name='serviceaccount',
            name='identity_card',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='identity card'),
        ),
        migrations.AlterField(
            model_name='serviceaccount',
            name='identity_check',
            field=models.BooleanField(default=False, verbose_name='identity verified'),
        ),
        migrations.AlterField(
            model_name='serviceaccount',
            name='phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'The telephone number must be 11 numbers long')], verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='serviceaccount',
            name='photo',
            field=models.ImageField(blank=True, upload_to='servicePhoto', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='serviceaccount',
            name='vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sw_vehicles.Vehicle', verbose_name='vehicle'),
        ),
    ]
