# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 21:00
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sw_users', '0011_auto_20161123_0450'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientaccount',
            options={'verbose_name': 'cliente', 'verbose_name_plural': 'clientes'},
        ),
        migrations.AlterModelOptions(
            name='serviceaccount',
            options={'verbose_name': 'proveedor de servicio', 'verbose_name_plural': 'proveedor de servicios'},
        ),
        migrations.AlterField(
            model_name='clientaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado a las'),
        ),
        migrations.AlterField(
            model_name='clientaccount',
            name='phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'El número de teléfono debe tener 11 números de largo')], verbose_name='teléfono'),
        ),
        migrations.AlterField(
            model_name='clientaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='actualizado a las'),
        ),
        migrations.AlterField(
            model_name='serviceaccount',
            name='address',
            field=models.CharField(max_length=100, verbose_name='dirección'),
        ),
        migrations.AlterField(
            model_name='serviceaccount',
            name='balance',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6, verbose_name='saldo'),
        ),
        migrations.AlterField(
            model_name='serviceaccount',
            name='bankaccount',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sw_payments.BankAccount', verbose_name='cuenta bancaria'),
        ),
        migrations.AlterField(
            model_name='serviceaccount',
            name='birthdate',
            field=models.DateField(verbose_name='fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='serviceaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado a las'),
        ),
        migrations.AlterField(
            model_name='serviceaccount',
            name='driver_license',
            field=models.ImageField(blank=True, upload_to='license', verbose_name='licencia de conducir'),
        ),
        migrations.AlterField(
            model_name='serviceaccount',
            name='identity_card',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='cédula de identidad'),
        ),
        migrations.AlterField(
            model_name='serviceaccount',
            name='identity_check',
            field=models.BooleanField(default=False, verbose_name='identidad verificada'),
        ),
        migrations.AlterField(
            model_name='serviceaccount',
            name='last_location_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='última fecha de ubicación'),
        ),
        migrations.AlterField(
            model_name='serviceaccount',
            name='last_location_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='último punto de ubicación'),
        ),
        migrations.AlterField(
            model_name='serviceaccount',
            name='phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'El número de teléfono debe tener 11 números de largo')], verbose_name='teléfono'),
        ),
        migrations.AlterField(
            model_name='serviceaccount',
            name='photo',
            field=models.ImageField(blank=True, upload_to='servicePhoto', verbose_name='foto'),
        ),
        migrations.AlterField(
            model_name='serviceaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='actualizado a las'),
        ),
        migrations.AlterField(
            model_name='serviceaccount',
            name='vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sw_vehicles.Vehicle', verbose_name='vehículo'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='check_mail',
            field=models.BooleanField(default=False, verbose_name='correo chekeado'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='client',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='sw_users.ClientAccount', verbose_name='cliente'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='correo electrónico'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='service',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='sw_users.ServiceAccount', verbose_name='proveedor de servicio'),
        ),
    ]
