# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-23 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reputation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentary', models.CharField(max_length=100, verbose_name='Comentario')),
                ('score', models.IntegerField(verbose_name='Puntuacion')),
            ],
            options={
                'verbose_name': 'Reputación',
                'verbose_name_plural': 'Reputacion',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo1', models.ImageField(blank=True, upload_to='shipmentPhoto', verbose_name='Foto')),
                ('photo2', models.ImageField(blank=True, upload_to='shipmentPhoto', verbose_name='Foto')),
                ('photo3', models.ImageField(blank=True, upload_to='shipmentPhoto', verbose_name='Foto')),
                ('tags', models.CharField(max_length=100, verbose_name='Etiquetas')),
                ('receiver', models.CharField(max_length=100, verbose_name='Receptor')),
                ('origin', models.CharField(max_length=100, verbose_name='Origen')),
                ('destination', models.CharField(max_length=100, verbose_name='Destino')),
                ('insured_value', models.DecimalField(
                    decimal_places=2,
                    default=0,
                    max_digits=6,
                    verbose_name='Valor asegurado')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Precio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Envio',
                'verbose_name_plural': 'Envios',
            },
        ),
        migrations.CreateModel(
            name='ShipmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.CharField(max_length=100, verbose_name='Descripción')),
                ('codename', models.CharField(max_length=100, verbose_name='Codigo')),
                ('icon', models.CharField(max_length=100, verbose_name='Icono')),
                ('insured_value', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor asegurado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de envio',
                'verbose_name_plural': 'Tipos de envios',
            },
        ),
    ]
