# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-23 03:13
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sw_shipments', '0001_initial'),
        ('sw_users', '0001_initial'),
        ('sw_vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sw_users.ClientAccount', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='packagetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sw_vehicles.PackageType', verbose_name='Tipo de paquete'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='reputation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sw_shipments.Reputation', verbose_name='Reputation'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sw_users.ServiceAccount', verbose_name='Prestador de servicio'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipmenttype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sw_shipments.ShipmentType', verbose_name='Tipo de envio'),
        ),
    ]
