# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 02:01
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sw_shipments', '0002_auto_20161022_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('value', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Metrica',
                'verbose_name_plural': 'Metricas',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('codename', models.CharField(max_length=100, verbose_name='Codigo')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.AddField(
            model_name='shipmenttype',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6, verbose_name='Precio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='status',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sw_shipments.Status', verbose_name='Status'),
            preserve_default=False,
        ),
    ]
