# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sw_shipments', '0009_auto_20161130_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='insured_value',
        ),
        migrations.AddField(
            model_name='shipment',
            name='insured',
            field=models.BooleanField(default=False, verbose_name='valor asegurado'),
        ),
    ]
