# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sw_shipments', '0010_auto_20161130_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='precio'),
        ),
    ]
