# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 21:00
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sw_payments', '0004_auto_20161123_0442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'verbose_name': 'banco', 'verbose_name_plural': 'bancos'},
        ),
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'verbose_name': 'cuenta bancaria', 'verbose_name_plural': 'cuentas bancarias'},
        ),
        migrations.AlterField(
            model_name='bank',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado a las'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='actualizado a las'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sw_payments.Bank', verbose_name='banco'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado a las'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='holder',
            field=models.CharField(max_length=100, verbose_name='titular'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='identity_card',
            field=models.CharField(max_length=8, verbose_name='cédula de identidad'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='number',
            field=models.CharField(max_length=20, verbose_name='número'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='type',
            field=models.IntegerField(choices=[[1, 'Ahorro'], [2, 'Corriente']], verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='actualizado a las'),
        ),
    ]
