# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sw_vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagetype',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6, verbose_name='Precio'),
            preserve_default=False,
        ),
    ]
