# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 17:49
from __future__ import unicode_literals

import colorful.fields
import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sw_vehicles', '0002_packagetype_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagetype',
            name='height_max',
        ),
        migrations.RemoveField(
            model_name='packagetype',
            name='height_min',
        ),
        migrations.RemoveField(
            model_name='packagetype',
            name='weight_max',
        ),
        migrations.RemoveField(
            model_name='packagetype',
            name='weight_min',
        ),
        migrations.RemoveField(
            model_name='packagetype',
            name='width_max',
        ),
        migrations.RemoveField(
            model_name='packagetype',
            name='width_min',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='photo3',
        ),
        migrations.AddField(
            model_name='packagetype',
            name='height',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(default=(0, 0), verbose_name='Altura'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packagetype',
            name='weight',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(default=(0, 0), verbose_name='Peso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packagetype',
            name='width',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(default=(0, 0), verbose_name='Anchura'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='color',
            field=colorful.fields.RGBColorField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehiclecategory',
            name='description',
            field=models.TextField(max_length=200, verbose_name='Descripción'),
        ),
    ]
