# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sw_vehicles', '0005_auto_20161122_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagetype',
            name='codename',
            field=models.CharField(max_length=100, unique=True, verbose_name='nombre en código'),
        ),
        migrations.AlterField(
            model_name='packagetype',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='nombre'),
        ),
    ]
