# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sw_vehicles', '0006_auto_20161122_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagetype',
            name='description',
            field=models.TextField(max_length=200, verbose_name='descripción'),
        ),
    ]
