# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 04:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sw_vehicles', '0007_auto_20161123_0209'),
        ('sw_vehicles', '0007_auto_20161122_0605'),
    ]

    operations = [
    ]
